version: '3.8'
services:
  mongodb:
    image: mongo:latest # Use the official mongo image from Docker Hub
    container_name: mongodb_container
    ports:
      - "27017:27017" # Map host port 27017 to container port 27017
    volumes:
      - mongodb_data:/data/db # Persist data in a Docker volume
    restart: unless-stopped # Ensure the container restarts automatically unless stopped explicitly

volumes:
  mongodb_data:
    driver: local # Define the volume
